2.5

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,59 @@
 #!/bin/bash
-DOCKER_BUILDKIT=1 docker build \
-    --tag birnbaum01/hiwi-jpeg-investigator \
-    .
-exit $?
+echo "[JPEG INVESTIGATOR BUILD] building docker image..."
+DOCKER_BUILDKIT=1 docker build --tag birnbaum01/hiwi-jpeg-investigator .
+err_lvl=$?
+
+if [ "$err_lvl" != "0" ]; then
+    echo "Failed to build docker image!"
+    exit $err_lvl
+fi
+
+echo "[JPEG INVESTIGATOR BUILD] creating docker executables..."
+cp "./scripts/investigate-jpeg" "./investigate-jpeg" && chmod +x "./investigate-jpeg"
+cp "./scripts/investigate-all" "./investigate-all" && chmod +x "./investigate-all"
+cp "./scripts/classify-all" "./classify-all" && chmod +x "./classify-all"
+
+echo "[JPEG INVESTIGATOR BUILD] creating native tarball..."
+EXPORT_TAR="jpeg-investigator-release.tar.gz"
+EXPORT_DIR="jpeg-investigator-release"
+EXPORT_APT_DEPS="$EXPORT_DIR/apt-dependencies.txt"
+EXPORT_PIP_DEPS="$EXPORT_DIR/pip-requirements.txt"
+EXECUTABLE="$EXPORT_DIR/investigate-jpeg"
+
+if [ -d "$EXPORT_DIR" ]; then
+    rm -drf "$EXPORT_DIR"
+fi
+if [ -f "$EXPORT_TAR" ]; then
+    rm -f "$EXPORT_TAR"
+fi
+
+#copy tool and requirements
+cp -R "./jpeg-investigator" "$EXPORT_DIR"
+echo "python3.10" >> "$EXPORT_APT_DEPS"
+echo "python3-pip" >> "$EXPORT_APT_DEPS"
+echo "exiftool" >> "$EXPORT_APT_DEPS"
+echo "texttable" >> "$EXPORT_PIP_DEPS"
+
+#create example usage structure
+mkdir "$EXPORT_DIR/workdir"
+find workdir -mindepth 1 -maxdepth 1 -type f -exec cp "{}" "$EXPORT_DIR/{}" \;
+
+#exchange main executable to native version
+rm -f "$EXPORT_DIR/entrypoint.sh"
+echo "#!/bin/bash" > "$EXECUTABLE"
+echo "python3 -u ./jpeg_investigator.py \"\$@\"" >> "$EXECUTABLE"
+echo "exit \$?" >> "$EXECUTABLE"
+chmod +x "$EXECUTABLE"
+
+cp "./scripts/investigate-all" "$EXPORT_DIR/investigate-all" && chmod +x "$EXPORT_DIR/investigate-all"
+cp "./scripts/classify-all" "$EXPORT_DIR/classify-all" && chmod +x "$EXPORT_DIR/classify-all"
+
+#tar -cvzf "$EXPORT_TAR" "$EXPORT_DIR"
+#rm -drf "$EXPORT_DIR"
+
+#TODO: write run scripts after successful build
+#   investigate-jpeg, investigate-all, classify-all; last both copied to release!
+#TODO: update readme and include with release!
+
+echo "Done!"
+exit 0
diff --git a/scripts/classify-all b/scripts/classify-all
--- a/scripts/classify-all
+++ b/scripts/classify-all
@@ -1,37 +1,32 @@
 #!/bin/bash
-#TODO: write in Python...
 if [ "$#" != "1" ]; then
-    echo "Syntax: ./classify-segment-contents.sh <segments: csv>"
-    echo "  e.g.: ./classify-segment-contents.sh dqt"
-    echo "        ./classify-segment-contents.sh dqt,sof"
+    echo "Syntax: ./classify-all <segments: csv>"
+    echo "  e.g.  ./classify-all dqt"
+    echo "        ./classify-all dqt,sof"
     exit 1
 fi
+if [ ! -d "./workdir" ]; then
+    echo "ERROR: Could not find directory '$(realpath ./workdir)'!"
+    exit 20
+fi
 
-cd "./workdir"
-files=`ls *.jpg`
-cd "../"
-
+echo "Investigating JPEG files..."
+jpg_files=`ls ./workdir/*.jpg`
 if [ -d "./workdir/segment-classifier" ]; then
     rm -drf "./workdir/segment-classifier"
 fi
-
-echo "JPEG investigator is running..."
-
-./investigate-jpeg -ed segment-classifier -es "$1" -f -s $files
+./investigate-jpeg --extract_directory "./workdir/segment-classifier" --extract_segments "$1" --force --silent $jpg_files
 err_lvl=$?
-
 if [ "$err_lvl" != "0" ]; then
     echo "ERROR: JPEG investigator exited with a non-zero error-code!"
     exit $err_lvl
 fi
-
 if [ ! -d "./workdir/segment-classifier" ]; then
     echo "ERROR: No data source available!"
-    exit 20
+    exit 21
 fi
 
 echo "Running classification..."
-
 out_dir="./workdir/segment-classifier-hashmap"
 if [ -d "${out_dir}" ]; then
     rm -drf $out_dir
@@ -46,7 +41,7 @@ find "./workdir/segment-classifier" -mindepth 1 -maxdepth 1 -type d -print0 |
         jpg_file="./workdir/${identifier}.jpg"
         if [ ! -f "${jpg_file}" ]; then
             echo "ERROR: Could not find '${jpg_file}'!"
-            exit 21
+            exit 22
         fi
 
         # read extracted segments
@@ -62,19 +57,13 @@ find "./workdir/segment-classifier" -mindepth 1 -maxdepth 1 -type d -print0 |
         # copy
         checksum_dir="${out_dir}/${checksum}"
         if [ ! -d "${checksum_dir}" ]; then
-            echo "new class: ${checksum}"
+            echo "  New class: ${checksum}"
             mkdir $checksum_dir
-
             cp -r "./workdir/segment-classifier/${identifier}/." "${checksum_dir}"
         fi
-
         checksum_file="${checksum_dir}/${identifier}.jpg"
-        echo "classified ${jpg_file} as ${checksum}"
-        #mv/cp
+        echo "  Classified ${jpg_file} as ${checksum}"
         cp "${jpg_file}" "${checksum_file}"
-        echo " --> ${checksum_file}"
     done
-
 echo "Done!"
-
 exit 0
